const NEW_MITIGATION_REQ = "NEW_MITIGATION_REQ";
const MITIGATION_REQ_DECLINED = "MITIGATION_REQ_DECLINED";
const MITIGATION_REQ_ACCEPTED = "MITIGATION_REQ_ACCEPTED";
const MITIGATION_REQ_IN_PROGRESS = "MITIGATION_REQ_IN_PROGRESS";
const MITIGATION_REQ_SUCCESSFUL = "MITIGATION_REQ_SUCCESSFUL";

export default {
    NEW_MITIGATION_REQ: NEW_MITIGATION_REQ,
    MITIGATION_REQ_DECLINED: MITIGATION_REQ_DECLINED,
    MITIGATION_REQ_ACCEPTED: MITIGATION_REQ_ACCEPTED,
    MITIGATION_REQ_IN_PROGRESS: MITIGATION_REQ_IN_PROGRESS,
    MITIGATION_REQ_SUCCESSFUL: MITIGATION_REQ_SUCCESSFUL
}