const NEW_ALARM = "NEW_ALARM";
const ALARM_IGNORED = "ALARM_IGNORED";
const REQ_MITIGATION_REQUESTED = "REQ_MITIGATION_REQUESTED";
const REQ_MITIGATION_ACCEPTED = "REQ_MITIGATION_ACCEPTED";
const REQ_MITIGATION_IN_PROGRESS = "REQ_MITIGATION_IN_PROGRESS";
const REQ_MITIGATION_SUCCESSFUL = "REQ_MITIGATION_SUCCESSFUL";

export default {
    NEW_ALARM: NEW_ALARM,
    ALARM_IGNORED: ALARM_IGNORED,
    REQ_MITIGATION_REQUESTED: REQ_MITIGATION_REQUESTED,
    REQ_MITIGATION_ACCEPTED: REQ_MITIGATION_ACCEPTED,
    REQ_MITIGATION_IN_PROGRESS: REQ_MITIGATION_IN_PROGRESS,
    REQ_MITIGATION_SUCCESSFUL: REQ_MITIGATION_SUCCESSFUL
}
