// Inbound Mitigation Requests
const NEW_MITIGATION_REQ = "NEW_MITIGATION_REQ";
const MITIGATION_REQ_DECLINED = "MITIGATION_REQ_DECLINED";
const MITIGATION_REQ_ACCEPTED = "MITIGATION_REQ_ACCEPTED";
const MITIGATION_REQ_IN_PROGRESS = "MITIGATION_REQ_IN_PROGRESS";
const MITIGATION_REQ_SUCCESSFUL = "MITIGATION_REQ_SUCCESSFUL";
// Outbound Request Mitigations
const NEW_ALARM = "NEW_ALARM";
const ALARM_IGNORED = "ALARM_IGNORED";
const REQ_MITIGATION_REQUESTED = "REQ_MITIGATION_REQUESTED";
const REQ_MITIGATION_ACCEPTED = "REQ_MITIGATION_ACCEPTED";
const REQ_MITIGATION_DECLINED = "REQ_MITIGATION_DECLINED";
const REQ_MITIGATION_IN_PROGRESS = "REQ_MITIGATION_IN_PROGRESS";
const REQ_MITIGATION_SUCCESSFUL = "REQ_MITIGATION_SUCCESSFUL";

export default {
    NEW_MITIGATION_REQ: NEW_MITIGATION_REQ,
    MITIGATION_REQ_DECLINED: MITIGATION_REQ_DECLINED,
    MITIGATION_REQ_ACCEPTED: MITIGATION_REQ_ACCEPTED,
    MITIGATION_REQ_IN_PROGRESS: MITIGATION_REQ_IN_PROGRESS,
    MITIGATION_REQ_SUCCESSFUL: MITIGATION_REQ_SUCCESSFUL,
    NEW_ALARM: NEW_ALARM,
    ALARM_IGNORED: ALARM_IGNORED,
    REQ_MITIGATION_REQUESTED: REQ_MITIGATION_REQUESTED,
    REQ_MITIGATION_ACCEPTED: REQ_MITIGATION_ACCEPTED,
    REQ_MITIGATION_DECLINED: REQ_MITIGATION_DECLINED,
    REQ_MITIGATION_IN_PROGRESS: REQ_MITIGATION_IN_PROGRESS,
    REQ_MITIGATION_SUCCESSFUL: REQ_MITIGATION_SUCCESSFUL
}